### ISSUE TITLE
How to use versioningit in conda-forge packages?

### ISSUE THREAD

**Issue by AAriam** [jwodder/versioningit#103]
Hi,

conda-forge asks you to [build from tarballs, not repos](https://conda-forge.org/docs/maintainer/adding_pkgs/#build-from-tarballs-not-repos). This means the git repo is not available during build. Instead, the version is statically declared in the conda recipe. So, how can one use versioningit in a Python package deployed to conda-forge?

I see there are several packages using versioningit on conda-forge, but I can't figure out how to make it work. As far as I understood, the best you can do is to define `tool.versioningit.default-version` so at least the build doesn't fail, but then the actual version will never match the version generated by versioningit, unless you manually change the default version before each build, which defies the whole purpose of the tool. Is this correct, or am I missing something?

Thanks a lot!

**Comment by jwodder** [comment]
Assuming your package is on PyPI, I believe the recommended practice is to build from an sdist of the project downloaded from there, and sdists of versioningit-enabled projects will contain the proper version in the `PKG-INFO` file.  You then just need to list `versioningit` in the host requirements alongside the build backend.

For example, for a PyPI package built with setuptools and versioningit, your `recipe/meta.yaml` would start out with:

```yaml
{% set name = "package-name" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: # fill in

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioningit
```
