### ISSUE TITLE
How to format version if the repository’s current state is an exact tag match

### ISSUE THREAD

**Issue by mzebrak** [jwodder/versioningit#42]
Is there an option to format the version like the `[tool.versioningit.format]` does, but when there is no distance and is no dirty?

I need to do something like:
```toml
[tool.versioningit.format]
base = "{base_version}+{vcs}{rev}.{author_date:%Y%m%dT%H%M%S}"
distance = "{base_version}.post{distance}+{vcs}{rev}.{author_date:%Y%m%dT%H%M%S}"
dirty = "{base_version}.dev+{vcs}{rev}.{author_date:%Y%m%dT%H%M%S}"
distance-dirty = "{base_version}.dev{distance}+{vcs}{rev}.{author_date:%Y%m%dT%H%M%S}"
```
